# WLAN Pi Wireless Engineering Toolkit
# WPA3 / Wi-Fi 7 Client Profiler Profile

[GENERAL]

channel: 36
interface: wlan0
ssid: WIFI7-PROFILER
passphrase: profiler1234

security_mode: ft-wpa3-mixed
ft_disabled: False

he_disabled: False
be_disabled: False

profiler_tlv_disabled: False
listen_only: False
hostname_ssid: False

files_path: /var/www/html/profiler
debug: False
